---

- name: install haproxy
  apt:
    name: haproxy
    state: latest

#make sure we have enable in /etc/default/haproxy
- name: enable haproxy
  lineinfile:
    dest: /etc/default/haproxy
    regexp: "^ENABLED.*$"
    line: "ENABLED=1"
    state: present

# copy haproxy config file
- name: configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 644
    validate: haproxy -f %s -c -q
  notify: restart haproxy

# enable haproxy service
- name: enable haproxy
  service:
    name: haproxy
    state: started
    enabled: yes


...
