---

#install apache from a package list defined in defaults
- name: install apache2 packages
  apt:
    name: "{{ apache_packages }}"
    state: latest

# enable apache service
- name: enable apache2
  service:
   name: apache2
   state: started
   enabled: yes

#enable apache from a package list defined in defaults
- name: enable apache2 packages
  file:
    src: "{{ apache_config_path }}/mods-available/{{ item }}"
    dest: "{{ apache_config_path }}/mods-enabled/{{ item }}"
    state: link
  with_items: "{{ apache_mods_enabled }}"
  notify: restart apache2

# copy apache config file to sites available
- name: configure apache2 sites-available
  template:
    src: "{{ apache_vhost_template }}"
    dest: "{{ apache_config_path }}/sites-available/{{ apache_vhost_file }}"
    owner: root
    group: root
    mode: 644
  notify: restart apache2

# link apache config file to sites enabled
- name: link apache2 sites-enabled
  file:
    src: "{{ apache_config_path }}/sites-available/{{ apache_vhost_file }}"
    dest: "{{ apache_config_path }}/sites-enabled/{{ apache_vhost_file }}"
    state: link
  notify: restart apache2

# remove apache default config file link
- name: link apache2 sites-enabled
  file:
    path: "{{ apache_config_path }}/sites-enabled/000-default.conf"
    state: absent
  notify: restart apache2

...
