---

- name: Install unzip
  apt:
    name: unzip
    state: latest

- name: check if wp is downloaded
  stat:
    path: "{{ wp_download_path }}"
  register: wp_download_present

- name: download wp
  get_url:
    url: "{{ wp_download_url }}"
    dest: "{{ wp_download_path }}"
  when: wp_download_present.stat.exists == False

- name: uncompress wp
  unarchive:
    src: "{{ wp_download_path }}"
    dest: "{{ wp_webserver_path }}"
    copy: no

- name: Configure wp settings file
  template:
    src: wp-config.php.j2
    dest: "{{ wp_webserver_wordpress_path }}/wp-config.php"
...
