---

apache_packages:
  - apache2
  - apache2-utils

apache_mods_enabled:
  - rewrite.load

#Apache settings
#NOTE: {{ webserver_root }} is defined as a group variable in group_vars/webservers.yml

apache_daemon: apache2
apache_daemon_path: /usr/sbin
apache_config_path: /etc/apache2/
apache_document_root: "{{ webserver_root }}"
apache_vhost_template: vhosts.conf.j2
apache_vhost_file: vhosts.conf

apache_listen_ip: "*"
apache_listen_port: "80"

apache_global_vhost_settings: |
  DirectoryIndex index.php index.html

apache_vhosts:
  - servername: "test.local"
    documentroot: "{{ webserver_root }}"


apache_allow_override: "All"
apache_options: "-Indexes +FollowSymLinks"


...
