---
mysql_packages:
  - mysql-server
  - mysql-common
# IMPORTANT: this role does NOT work with ansible <2.8.0
# python3-pip is required to install PyMySQL, which is required by mysql_user (as of ansible 2.8.0)
  - python3-pip

mysql_python_modules:
  - PyMySQL

mysql_service: mysql
...
